# Generated by Django 3.0.7 on 2020-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=150)),
                ('addr', models.CharField(max_length=250)),
            ],
        ),
    ]
